### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by battlemidget** [jonathantneal/precss#28]
When attempting to build a es6 project with gulp and postcss, precss will fail with the following error:

```
/home/adam/Projects/astokes.org/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:43
        if (typeof css === 'object' && css.type === 'root') {
                                          ^

TypeError: Cannot read property 'type' of null
    at new LazyResult (/home/adam/Projects/astokes.org/node_modules/gulp-postcss/node_modules/postcss/lib/lazy-result.js:43:43)
    at Processor.process (/home/adam/Projects/astokes.org/node_modules/gulp-postcss/node_modules/postcss/lib/processor.js:36:16)
    at Transform.stream._transform (/home/adam/Projects/astokes.org/node_modules/gulp-postcss/index.js:44:8)
    at Transform._read (_stream_transform.js:167:10)
    at Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:292:12)
    at clearBuffer (_stream_writable.js:396:7)
    at onwrite (_stream_writable.js:331:7)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at afterTransform (_stream_transform.js:79:5)
[~/P/astokes.org]                                 
```

I'm running node v3.2.0 (iojs), babel 5.8.23, gulp v3.9.0. I'm utilizing gulp/babel to process the site:

**gulpfile.babel.js**

``` js
"use strict";

import gulp from "gulp";
import eslint from "gulp-eslint";
import uglify from "gulp-uglify";
import minifycss from "gulp-minify-css";
import concat from "gulp-concat";
import del from "del";
import postcss from "gulp-postcss";
import precss from "precss";
import cssnext from "cssnext";
import cssnano from "cssnano";
import rucksack from "gulp-rucksack";

let css = [
    "bower_components/normalize-css/normalize.css",
    "bower_components/highlightjs/styles/obsidian.css",
    "assets/css/*"
];

gulp.task('styles', () => {
    return gulp.src(css)
        .pipe(postcss([
            precss(),
            cssnext(),
            cssnano()]))
        .pipe(rucksack())
        .pipe(minifycss())
        .pipe(concat('main.min.css'))
        .pipe(gulp.dest('public/css'));
});

let js = [
    "bower_components/jquery/dist/jquery.js",
    "bower_components/highlightjs/highlight.pack.js",
    "assets/js/main.js"
];

gulp.task('js', () => {
    return gulp.src(js)
        .pipe(uglify())
        .pipe(concat('main.min.js'))
        .pipe(gulp.dest('public/js'))
});

gulp.task('lint', () => {
    return gulp.src(['lib/**/*.js'])
        .pipe(eslint())
        .pipe(eslint.format())
        .pipe(eslint.failOnError())
});

gulp.task('clean', (cb) =>{
    del(['public'], cb);
});

gulp.task('default', ['clean', 'lint', 'styles', 'js']);
```

Is this something within precss, or my use of babel, or gulp itself? My project is hosted at if you needed more context around the setup https://github.com/battlemidget/astokes.org

**Comment by Jonjoe** [comment]
bump!

**Comment by jsanders** [comment]
@battlemidget / @Jonjoe: This seems to happen if you're using postcss and one of your css paths can't be found. So my guess is that one of your bower components is missing.

**Comment by jonathantneal** [comment]
Closing this due to inactivity, and because the minimum version of Node required by PostCSS is now v4, and because PreCSS has changed so much since this issue was created.
