### ISSUE TITLE
& not working in loops not working in 1.4

### ISSUE THREAD

**Issue by pmowrer** [jonathantneal/precss#52]
With the following:

```sass
div {
  @for $i from 0 to 100 by 5 {
    &.size-$i {
      flex: 0 0 $(i)%;
    }
  }
}
```
I get this error:
```js
Module build failed: TypeError: Cannot read property 'forEach' of undefined
    at transpileSelectors (<path>/node_modules/postcss-cssnext/node_modules/postcss-nesting/index.js:71:20)
    at <path>/node_modules/postcss-cssnext/node_modules/postcss-nesting/index.js:57:4
    at <path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:115:34
    at <path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:73:26
    at AtRule.each (<path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:60:22)
    at AtRule.walk (<path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:72:21)
    at <path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:76:32
    at Rule.each (<path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:60:22)
    at Rule.walk (<path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:72:21)
    at <path>/node_modules/postcss-loader/node_modules/postcss/lib/container.js:76:32
```

If I remove the `&`, it works fine.

Also, it **does work in the live demo**, but perhaps that runs a different version?

Using `@nest`, this particular problem goes away, but then the loop's variable interpolation doesn't work. Perhaps another bug?

```sass
div {
  @for $i from 0 to 100 by 5 {
    @nest &.size-$i {
      flex: 0 0 $(i)%;
    }
  }
}
```
Gives:
```css
div {
}
div.size-$i {
    flex: 0 0 0%
}
div.size-$i {
    flex: 0 0 5%
}
```

**Comment by pmowrer** [comment]
I guess this is actually an incompatibility issue with [cssnext](https://github.com/MoOx/postcss-cssnext). Closing.
